services:
  api_1:
    image: link-shortener-api
    build:
      context: .
      dockerfile: Dockerfile
    # command: fastapi dev app/main.py --host 0.0.0.0 --port 80
    command: fastapi run app/main.py --host 0.0.0.0 --port 80 --workers 4
    environment:
      SHARD_ID: 1
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/link_shortener
      BASE_URL: http://127.0.0.1:8000
    ports:
      - "8000:80"
    volumes:
      - ./app:/app/app
    depends_on:
      - redis

  redis:
    image: redis:8
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    restart: unless-stopped

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: link_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
