services:
  api_1:
    image: link-shortener-api
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --workers 8 --no-access-log
    #command: fastapi run app/main.py --host 0.0.0.0 --port 80 --workers 8
    environment:
      SHARD_ID: 1
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql+psycopg://postgres:postgres@pgbouncer:5432/link_shortener
      BASE_URL: http://127.0.0.1:8000
    ports:
      - "8000:80"
    volumes:
      - ./app:/app/app
    cpus: "4.0"
    mem_limit: 2g
    depends_on:
      - redis

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    cpus: "0.5"
    mem_limit: 512m
    environment:
      REDIS_ARGS: >-
        --appendonly yes
        --maxmemory 384mb
        --maxmemory-policy volatile-lfu
    restart: unless-stopped

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: link_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    cpus: "2.0"
    mem_limit: 3g
    restart: unless-stopped

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: link_shortener
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 500
      DEFAULT_POOL_SIZE: 40
      RESERVE_POOL_SIZE: 10
      AUTH_TYPE: scram-sha-256
      ADMIN_USERS: postgres
    depends_on:
      - postgres
    ports:
      - "6432:5432"
    cpus: "0.5"
    mem_limit: 256m
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
