"""create alternate links table with no index

Revision ID: 86958792d402
Revises: 71418bcac042
Create Date: 2026-06-29 21:25:32.759501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '86958792d402'
down_revision: Union[str, Sequence[str], None] = '71418bcac042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links_no_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links_no_index')
    # ### end Alembic commands ###
